/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yundry;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class BerandaForm extends javax.swing.JFrame {

    /**
     * Creates new form BerandaForm
     */
    public BerandaForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_data();
        autonumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pberanda = new javax.swing.JPanel();
        txtberanda = new javax.swing.JLabel();
        pkaryawan = new javax.swing.JPanel();
        txtkaryawan = new javax.swing.JLabel();
        ppelanggan = new javax.swing.JPanel();
        txtpelanggan = new javax.swing.JLabel();
        ppendataan = new javax.swing.JPanel();
        txtpendataan = new javax.swing.JLabel();
        ppembayaran = new javax.swing.JPanel();
        txtpembayaran = new javax.swing.JLabel();
        ppengambilan = new javax.swing.JPanel();
        txtpengambilan = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbberanda = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidpaket = new javax.swing.JTextField();
        txtnamapaket = new javax.swing.JTextField();
        txtketerangan = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        btnbatal = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 207, 226));

        jPanel2.setBackground(new java.awt.Color(100, 152, 182));
        jPanel2.setPreferredSize(new java.awt.Dimension(248, 1024));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yundry/Logo1.png"))); // NOI18N

        pberanda.setBackground(new java.awt.Color(215, 206, 156));
        pberanda.setPreferredSize(new java.awt.Dimension(248, 69));
        pberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pberandaMouseClicked(evt);
            }
        });

        txtberanda.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtberanda.setText("BERANDA");
        txtberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtberandaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pberandaLayout = new javax.swing.GroupLayout(pberanda);
        pberanda.setLayout(pberandaLayout);
        pberandaLayout.setHorizontalGroup(
            pberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pberandaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txtberanda)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pberandaLayout.setVerticalGroup(
            pberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pberandaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtberanda)
                .addContainerGap())
        );

        pkaryawan.setBackground(new java.awt.Color(215, 206, 156));
        pkaryawan.setPreferredSize(new java.awt.Dimension(248, 69));
        pkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pkaryawanMouseClicked(evt);
            }
        });

        txtkaryawan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtkaryawan.setText("KARYAWAN");
        txtkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtkaryawanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pkaryawanLayout = new javax.swing.GroupLayout(pkaryawan);
        pkaryawan.setLayout(pkaryawanLayout);
        pkaryawanLayout.setHorizontalGroup(
            pkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkaryawanLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtkaryawan)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pkaryawanLayout.setVerticalGroup(
            pkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkaryawanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtkaryawan)
                .addContainerGap())
        );

        ppelanggan.setBackground(new java.awt.Color(215, 206, 156));
        ppelanggan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppelangganMouseClicked(evt);
            }
        });

        txtpelanggan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpelanggan.setText("PELANGGAN");
        txtpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpelangganMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppelangganLayout = new javax.swing.GroupLayout(ppelanggan);
        ppelanggan.setLayout(ppelangganLayout);
        ppelangganLayout.setHorizontalGroup(
            ppelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppelangganLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtpelanggan)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        ppelangganLayout.setVerticalGroup(
            ppelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppelangganLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpelanggan)
                .addContainerGap())
        );

        ppendataan.setBackground(new java.awt.Color(215, 206, 156));
        ppendataan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppendataanMouseClicked(evt);
            }
        });

        txtpendataan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpendataan.setText("PENDATAAN");
        txtpendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpendataanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppendataanLayout = new javax.swing.GroupLayout(ppendataan);
        ppendataan.setLayout(ppendataanLayout);
        ppendataanLayout.setHorizontalGroup(
            ppendataanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppendataanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtpendataan)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        ppendataanLayout.setVerticalGroup(
            ppendataanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppendataanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpendataan)
                .addContainerGap())
        );

        ppembayaran.setBackground(new java.awt.Color(215, 206, 156));
        ppembayaran.setPreferredSize(new java.awt.Dimension(248, 69));
        ppembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppembayaranMouseClicked(evt);
            }
        });

        txtpembayaran.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpembayaran.setText("PEMBAYARAN");
        txtpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpembayaranMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppembayaranLayout = new javax.swing.GroupLayout(ppembayaran);
        ppembayaran.setLayout(ppembayaranLayout);
        ppembayaranLayout.setHorizontalGroup(
            ppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppembayaranLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtpembayaran)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ppembayaranLayout.setVerticalGroup(
            ppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppembayaranLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpembayaran)
                .addContainerGap())
        );

        ppengambilan.setBackground(new java.awt.Color(215, 206, 156));
        ppengambilan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppengambilanMouseClicked(evt);
            }
        });

        txtpengambilan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpengambilan.setText("PENGAMBILAN");
        txtpengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpengambilanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppengambilanLayout = new javax.swing.GroupLayout(ppengambilan);
        ppengambilan.setLayout(ppengambilanLayout);
        ppengambilanLayout.setHorizontalGroup(
            ppengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppengambilanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtpengambilan)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        ppengambilanLayout.setVerticalGroup(
            ppengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppengambilanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpengambilan)
                .addContainerGap())
        );

        btnlogout.setBackground(new java.awt.Color(181, 156, 24));
        btnlogout.setText("LOGOUT");
        btnlogout.setPreferredSize(new java.awt.Dimension(137, 38));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppendataan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(pberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppendataan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel2.setText("WELCOME");

        btnsimpan.setBackground(new java.awt.Color(253, 234, 127));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(253, 234, 127));
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(253, 234, 127));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tbberanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbberandaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbberanda);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel3.setText("Yundry adalah singkat dari yuk ngelaundry yang di desain untuk aplikasi destop laundry.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel4.setText("kami akan memberikan pelayanan yang terbaik untuk pelangan. ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel5.setText("Id Paket");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel6.setText("Nama Paket");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel7.setText("Keterangan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel8.setText("Harga");

        txtidpaket.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtidpaket.setPreferredSize(new java.awt.Dimension(433, 36));

        txtnamapaket.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtnamapaket.setPreferredSize(new java.awt.Dimension(433, 36));

        txtketerangan.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtketerangan.setPreferredSize(new java.awt.Dimension(433, 36));

        txtharga.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtharga.setPreferredSize(new java.awt.Dimension(433, 36));

        btnbatal.setBackground(new java.awt.Color(253, 234, 127));
        btnbatal.setText("BATAL");
        btnbatal.setPreferredSize(new java.awt.Dimension(91, 29));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(125, 125, 125)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidpaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnamapaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtketerangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(112, 112, 112)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtidpaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnamapaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnedit))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapus)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtberandaMouseClicked
        // TODO add your handling code here:
        BerandaForm rgf = new BerandaForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtberandaMouseClicked

    private void pberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pberandaMouseClicked
        // TODO add your handling code here:
        BerandaForm rgf = new BerandaForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pberandaMouseClicked

    private void txtkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkaryawanMouseClicked
        // TODO add your handling code here:
        KaryawanForm rgf = new KaryawanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtkaryawanMouseClicked

    private void pkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkaryawanMouseClicked
        // TODO add your handling code here:
        KaryawanForm rgf = new KaryawanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pkaryawanMouseClicked

    private void txtpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpelangganMouseClicked
        // TODO add your handling code here:
        PelangganForm rgf = new PelangganForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpelangganMouseClicked

    private void ppelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppelangganMouseClicked
        // TODO add your handling code here:
        PelangganForm rgf = new PelangganForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppelangganMouseClicked

    private void txtpendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpendataanMouseClicked
        // TODO add your handling code here:
        PendataanForm rgf = new PendataanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpendataanMouseClicked

    private void ppendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppendataanMouseClicked
        // TODO add your handling code here:
        PendataanForm rgf = new PendataanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppendataanMouseClicked

    private void txtpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpembayaranMouseClicked
        // TODO add your handling code here:
        PembayaranForm rgf = new PembayaranForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpembayaranMouseClicked

    private void ppembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppembayaranMouseClicked
        // TODO add your handling code here:
        PembayaranForm rgf = new PembayaranForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppembayaranMouseClicked

    private void txtpengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpengambilanMouseClicked
        // TODO add your handling code here:
        PengambilanForm rgf = new PengambilanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpengambilanMouseClicked

    private void ppengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppengambilanMouseClicked
        // TODO add your handling code here:
        PengambilanForm rgf = new PengambilanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppengambilanMouseClicked

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,
            "Ingin Keluar?",
            "Keluar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, null, null);

        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program Akan Keluar");
            System.exit(0);
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql="insert into beranda values('"
            + txtidpaket.getText()+"','"
            + txtnamapaket.getText()+"','"
            + txtketerangan.getText()+"','"
            + txtharga.getText()+"')";

            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            tampil_data();
            autonumber();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql="update beranda set nama_paket ='"+ txtnamapaket.getText()
            +"', keterangan ='"+ txtketerangan.getText()
            +"', harga ='"+ txtharga.getText()
            +"' where id_paket ='"+ txtidpaket.getText()+"'";

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data berhasil di Koreksi");
            tampil_data();
            autonumber();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses Edit data Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql = "delete from beranda where id_paket='" + txtidpaket.getText()+"' ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            tampil_data();
            autonumber();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses Penghapusan Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbberandaMouseClicked
        // TODO add your handling code here:
        int tabel = tbberanda.getSelectedRow();
        txtidpaket.setText(tbberanda.getValueAt(tabel, 0).toString());
        txtnamapaket.setText(tbberanda.getValueAt(tabel, 1).toString());
        txtketerangan.setText(tbberanda.getValueAt(tabel, 2).toString());
        txtharga.setText(tbberanda.getValueAt(tabel, 3).toString());
    }//GEN-LAST:event_tbberandaMouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        txtnamapaket.setText("");
        txtketerangan.setText("");
        txtharga.setText("");
        txtnamapaket.requestFocus();
        autonumber();
    }//GEN-LAST:event_btnbatalActionPerformed

    public void tampil_data(){
        DefaultTableModel tabel=new DefaultTableModel();
        tabel.addColumn("URUT");
        tabel.addColumn("TEXT");

        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql="select *from beranda";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while (rs.next())
            {
            tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2)});
                
            }
            tbberanda.setModel(tabel);
            }
        catch (Exception e){
        }
    }
    
    public void autonumber(){
        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            Statement pst = conn.createStatement();
            String sql="select max(right(id_paket,3)) as no from beranda";
            ResultSet rs = pst.executeQuery(sql);
            
            while (rs.next())
            {
            if(rs.first() == false){
                txtidpaket.setText("PKT001");
            }else{
                rs.last();
                int set_id = rs.getInt(1)+1;
                String no = String.valueOf(set_id);
                int id_next = no.length();
                for(int i=0; i<3-id_next; i++){
                    no = "0" + no;
                }
                txtidpaket.setText("PKT"+ no);
            }   
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Auto Number Gagal", "Error", 2);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BerandaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BerandaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BerandaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BerandaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BerandaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pberanda;
    private javax.swing.JPanel pkaryawan;
    private javax.swing.JPanel ppelanggan;
    private javax.swing.JPanel ppembayaran;
    private javax.swing.JPanel ppendataan;
    private javax.swing.JPanel ppengambilan;
    private javax.swing.JTable tbberanda;
    private javax.swing.JLabel txtberanda;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidpaket;
    private javax.swing.JLabel txtkaryawan;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnamapaket;
    private javax.swing.JLabel txtpelanggan;
    private javax.swing.JLabel txtpembayaran;
    private javax.swing.JLabel txtpendataan;
    private javax.swing.JLabel txtpengambilan;
    // End of variables declaration//GEN-END:variables
}
