/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yundry;

import java.awt.Color;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class DaftarForm extends javax.swing.JFrame {

    private void display() {
        JFrame f = new JFrame("DaftarForm");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.add(this);
        f.pack();
        f.setExtendedState(f.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        f.setVisible(true);
    }
    /**
     * Creates new form DaftarForm
     */
    public DaftarForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        pspassword = new javax.swing.JPasswordField();
        lblogin = new javax.swing.JLabel();
        btndaftar = new javax.swing.JButton();
        txtnama = new javax.swing.JTextField();
        pskonfirmasi = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 207, 226));

        jPanel2.setBackground(new java.awt.Color(236, 223, 156));
        jPanel2.setPreferredSize(new java.awt.Dimension(1005, 659));

        jPanel3.setBackground(new java.awt.Color(215, 206, 156));
        jPanel3.setPreferredSize(new java.awt.Dimension(919, 602));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yundry/Logo.png"))); // NOI18N

        txtid.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        pspassword.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        pspassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pspasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pspasswordFocusLost(evt);
            }
        });

        lblogin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblogin.setText("Login");
        lblogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbloginMouseClicked(evt);
            }
        });

        btndaftar.setText("DAFTAR");
        btndaftar.setPreferredSize(new java.awt.Dimension(150, 40));
        btndaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaftarActionPerformed(evt);
            }
        });

        txtnama.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamaFocusLost(evt);
            }
        });

        pskonfirmasi.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        pskonfirmasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pskonfirmasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pskonfirmasiFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(218, 218, 218)
                .addComponent(lblogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pspassword, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(txtid)
                            .addComponent(txtnama)
                            .addComponent(pskonfirmasi)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(btndaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pspassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pskonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btndaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void lbloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbloginMouseClicked
        // TODO add your handling code here:
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbloginMouseClicked

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        // TODO add your handling code here:
        if(txtid.getText().trim().toLowerCase().equals("Masukkan User Id"))
        {
            txtid.setText("");
            txtid.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtidFocusGained

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        // TODO add your handling code here:
        if(txtid.getText().trim().equals("") || 
           txtid.getText().trim().toLowerCase().equals("Masukkan User Id"))
        {
            txtid.setText("Masukkan User Id");
            txtid.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtidFocusLost

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
        if(txtnama.getText().trim().toLowerCase().equals("Masukkan Nama"))
        {
            txtnama.setText("");
            txtnama.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtnamaFocusGained

    private void txtnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusLost
        // TODO add your handling code here:
        if(txtnama.getText().trim().equals("") || 
           txtnama.getText().trim().toLowerCase().equals("Masukkan Nama"))
        {
            txtnama.setText("Masukkan Nama");
            txtnama.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnamaFocusLost

    private void pspasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pspasswordFocusGained
        // TODO add your handling code here:
        String ps = String.valueOf(pspassword.getPassword());
        
        if(ps.trim().toLowerCase().equals("Masukkan Password"))
        {
            pspassword.setText("");
            pspassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_pspasswordFocusGained

    private void pspasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pspasswordFocusLost
        // TODO add your handling code here:
        String ps = String.valueOf(pspassword.getPassword());
        
        if(ps.trim().equals("") || 
           ps.trim().toLowerCase().equals("Masukkan Password"))
        {
            pspassword.setText("Masukkan Password");
            pspassword.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pspasswordFocusLost

    private void pskonfirmasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pskonfirmasiFocusGained
        // TODO add your handling code here:
        String ps = String.valueOf(pskonfirmasi.getPassword());
        
        if(ps.trim().toLowerCase().equals("Konfirmasi Password"))
        {
            pskonfirmasi.setText("");
            pskonfirmasi.setForeground(Color.black);
        }
    }//GEN-LAST:event_pskonfirmasiFocusGained

    private void pskonfirmasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pskonfirmasiFocusLost
        // TODO add your handling code here:
        String ps = String.valueOf(pskonfirmasi.getPassword());
        
        if(ps.trim().equals("") || 
           ps.trim().toLowerCase().equals("Konfirmasi Password"))
        {
            pskonfirmasi.setText("Konfirmasi Password");
            pskonfirmasi.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pskonfirmasiFocusLost

    private void btndaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaftarActionPerformed
        // TODO add your handling code here:
        String UserId = txtid.getText();
        String Nama = txtnama.getText();
        String Password = String.valueOf(pspassword.getPassword());
        String KonfirmasiPassword = String.valueOf(pskonfirmasi.getPassword());
        
        if(verifyFields())
        {
            PreparedStatement ps;
            ResultSet rs;
            String registerUserQuery = "INSERT INTO `login`(`user_id`, `nama`, `password`) VALUES (?,?,?)";
            
            try {
                ps = connection.getConnection().prepareStatement(registerUserQuery);
                
                ps.setString(1, UserId);
                ps.setString(2, Nama);
                ps.setString(3, Password);
                
                if(ps.executeUpdate() != 0){
                    JOptionPane.showMessageDialog(null, "Akun Berhasil Dibuat", "Pendaftaran Berhasil", 2);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Cek Data", "Pendaftaran Error", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(DaftarForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btndaftarActionPerformed
    public boolean verifyFields()
    {
        String UserId = txtid.getText();
        String Nama = txtnama.getText();
        String Password = String.valueOf(pspassword.getPassword());
        String KonfirmasiPassword = String.valueOf(pskonfirmasi.getPassword());
        
        if(UserId.trim().equals("Masukkan User Id") || Nama.trim().equals("Masukkan Nama") || 
           Password.trim().equals("Masukkan Password") || KonfirmasiPassword.trim().equals("Konfirmasi Password"))
        {
            JOptionPane.showMessageDialog(null, "Terdapat Data yang Kosong", "Pendaftaran Error",2);
            return false;
        }
        else if(!Password.equals(KonfirmasiPassword))
        {
            JOptionPane.showMessageDialog(null, "Konfirmasi Password Salah", "Pendaftaran Error",2);
            return false;
        }
        else{
            return true;
        }
    }
    
    public boolean CheckUserId(String UserId){
        PreparedStatement st;
        ResultSet rs;
        boolean userid_exist = false;
        
        String query = "SELECT * FROM `login` WHERE `user_id` = ?";
        
        try {
            st = connection.getConnection().prepareStatement(query);
            
            st.setString(1, UserId);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                userid_exist = true;
                JOptionPane.showMessageDialog(null, "User Id Sudah Digunakan", "Pendaftaran Error", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(DaftarForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userid_exist;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndaftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblogin;
    private javax.swing.JPasswordField pskonfirmasi;
    private javax.swing.JPasswordField pspassword;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

}
