/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yundry;

import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class PelangganForm extends javax.swing.JFrame {

    /**
     * Creates new form PelangganForm
     */
    public PelangganForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pberanda = new javax.swing.JPanel();
        txtberanda = new javax.swing.JLabel();
        pkaryawan = new javax.swing.JPanel();
        txtkaryawan = new javax.swing.JLabel();
        ppelanggan = new javax.swing.JPanel();
        txtpelanggan = new javax.swing.JLabel();
        ppendataan = new javax.swing.JPanel();
        txtpendataan = new javax.swing.JLabel();
        ppembayaran = new javax.swing.JPanel();
        txtpembayaran = new javax.swing.JLabel();
        ppengambilan = new javax.swing.JPanel();
        txtpengambilan = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpelanggan = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtidpelanggan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtnotelp = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 207, 226));

        jPanel2.setBackground(new java.awt.Color(100, 152, 182));
        jPanel2.setPreferredSize(new java.awt.Dimension(248, 1024));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yundry/Logo1.png"))); // NOI18N

        pberanda.setBackground(new java.awt.Color(215, 206, 156));
        pberanda.setPreferredSize(new java.awt.Dimension(248, 69));
        pberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pberandaMouseClicked(evt);
            }
        });

        txtberanda.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtberanda.setText("BERANDA");
        txtberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtberandaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pberandaLayout = new javax.swing.GroupLayout(pberanda);
        pberanda.setLayout(pberandaLayout);
        pberandaLayout.setHorizontalGroup(
            pberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pberandaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txtberanda)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pberandaLayout.setVerticalGroup(
            pberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pberandaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtberanda)
                .addContainerGap())
        );

        pkaryawan.setBackground(new java.awt.Color(215, 206, 156));
        pkaryawan.setPreferredSize(new java.awt.Dimension(248, 69));
        pkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pkaryawanMouseClicked(evt);
            }
        });

        txtkaryawan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtkaryawan.setText("KARYAWAN");
        txtkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtkaryawanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pkaryawanLayout = new javax.swing.GroupLayout(pkaryawan);
        pkaryawan.setLayout(pkaryawanLayout);
        pkaryawanLayout.setHorizontalGroup(
            pkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkaryawanLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtkaryawan)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pkaryawanLayout.setVerticalGroup(
            pkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkaryawanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtkaryawan)
                .addContainerGap())
        );

        ppelanggan.setBackground(new java.awt.Color(215, 206, 156));
        ppelanggan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppelangganMouseClicked(evt);
            }
        });

        txtpelanggan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpelanggan.setText("PELANGGAN");
        txtpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpelangganMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppelangganLayout = new javax.swing.GroupLayout(ppelanggan);
        ppelanggan.setLayout(ppelangganLayout);
        ppelangganLayout.setHorizontalGroup(
            ppelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppelangganLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtpelanggan)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        ppelangganLayout.setVerticalGroup(
            ppelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppelangganLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpelanggan)
                .addContainerGap())
        );

        ppendataan.setBackground(new java.awt.Color(215, 206, 156));
        ppendataan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppendataanMouseClicked(evt);
            }
        });

        txtpendataan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpendataan.setText("PENDATAAN");
        txtpendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpendataanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppendataanLayout = new javax.swing.GroupLayout(ppendataan);
        ppendataan.setLayout(ppendataanLayout);
        ppendataanLayout.setHorizontalGroup(
            ppendataanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppendataanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtpendataan)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        ppendataanLayout.setVerticalGroup(
            ppendataanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppendataanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpendataan)
                .addContainerGap())
        );

        ppembayaran.setBackground(new java.awt.Color(215, 206, 156));
        ppembayaran.setPreferredSize(new java.awt.Dimension(248, 69));
        ppembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppembayaranMouseClicked(evt);
            }
        });

        txtpembayaran.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpembayaran.setText("PEMBAYARAN");
        txtpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpembayaranMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppembayaranLayout = new javax.swing.GroupLayout(ppembayaran);
        ppembayaran.setLayout(ppembayaranLayout);
        ppembayaranLayout.setHorizontalGroup(
            ppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppembayaranLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtpembayaran)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ppembayaranLayout.setVerticalGroup(
            ppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppembayaranLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpembayaran)
                .addContainerGap())
        );

        ppengambilan.setBackground(new java.awt.Color(215, 206, 156));
        ppengambilan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppengambilanMouseClicked(evt);
            }
        });

        txtpengambilan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpengambilan.setText("PENGAMBILAN");
        txtpengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpengambilanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppengambilanLayout = new javax.swing.GroupLayout(ppengambilan);
        ppengambilan.setLayout(ppengambilanLayout);
        ppengambilanLayout.setHorizontalGroup(
            ppengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppengambilanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtpengambilan)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        ppengambilanLayout.setVerticalGroup(
            ppengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppengambilanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpengambilan)
                .addContainerGap())
        );

        btnlogout.setBackground(new java.awt.Color(181, 156, 24));
        btnlogout.setText("LOGOUT");
        btnlogout.setPreferredSize(new java.awt.Dimension(137, 38));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppendataan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(pberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppendataan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtcari.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtcari.setPreferredSize(new java.awt.Dimension(899, 36));

        btncari.setBackground(new java.awt.Color(253, 234, 127));
        btncari.setText("CARI");
        btncari.setPreferredSize(new java.awt.Dimension(151, 36));
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        tbpelanggan.setFont(new java.awt.Font("Sylfaen", 0, 13)); // NOI18N
        tbpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpelanggan);

        btnhapus.setBackground(new java.awt.Color(253, 234, 127));
        btnhapus.setText("HAPUS");
        btnhapus.setPreferredSize(new java.awt.Dimension(151, 36));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(253, 234, 127));
        btnedit.setText("EDIT");
        btnedit.setPreferredSize(new java.awt.Dimension(151, 36));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel8.setText("Id Pelanggan");

        txtidpelanggan.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtidpelanggan.setPreferredSize(new java.awt.Dimension(433, 36));

        jLabel10.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel10.setText("Nama Pelanggan");

        txtnama.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtnama.setPreferredSize(new java.awt.Dimension(433, 36));

        jLabel9.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel9.setText("Alamat");

        txtalamat.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtalamat.setPreferredSize(new java.awt.Dimension(433, 36));

        jLabel11.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel11.setText("No Telepon");

        txtnotelp.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtnotelp.setPreferredSize(new java.awt.Dimension(433, 36));

        btnsimpan.setBackground(new java.awt.Color(253, 234, 127));
        btnsimpan.setText("SIMPAN");
        btnsimpan.setPreferredSize(new java.awt.Dimension(151, 36));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(253, 234, 127));
        btnbatal.setText("BATAL");
        btnbatal.setPreferredSize(new java.awt.Dimension(151, 36));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(225, 225, 225))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtberandaMouseClicked
        // TODO add your handling code here:
        BerandaForm rgf = new BerandaForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtberandaMouseClicked

    private void pberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pberandaMouseClicked
        // TODO add your handling code here:
        BerandaForm rgf = new BerandaForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pberandaMouseClicked

    private void txtkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkaryawanMouseClicked
        // TODO add your handling code here:
        KaryawanForm rgf = new KaryawanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtkaryawanMouseClicked

    private void pkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkaryawanMouseClicked
        // TODO add your handling code here:
        KaryawanForm rgf = new KaryawanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pkaryawanMouseClicked

    private void txtpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpelangganMouseClicked
        // TODO add your handling code here:
        PelangganForm rgf = new PelangganForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpelangganMouseClicked

    private void ppelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppelangganMouseClicked
        // TODO add your handling code here:
        PelangganForm rgf = new PelangganForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppelangganMouseClicked

    private void txtpendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpendataanMouseClicked
        // TODO add your handling code here:
        PendataanForm rgf = new PendataanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpendataanMouseClicked

    private void ppendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppendataanMouseClicked
        // TODO add your handling code here:
        PendataanForm rgf = new PendataanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppendataanMouseClicked

    private void txtpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpembayaranMouseClicked
        // TODO add your handling code here:
        PembayaranForm rgf = new PembayaranForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpembayaranMouseClicked

    private void ppembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppembayaranMouseClicked
        // TODO add your handling code here:
        PembayaranForm rgf = new PembayaranForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppembayaranMouseClicked

    private void txtpengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpengambilanMouseClicked
        // TODO add your handling code here:
        PengambilanForm rgf = new PengambilanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpengambilanMouseClicked

    private void ppengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppengambilanMouseClicked
        // TODO add your handling code here:
        PengambilanForm rgf = new PengambilanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppengambilanMouseClicked

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Ingin Keluar?", 
                    "Keluar", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
        if(jawab == JOptionPane.YES_OPTION){
        JOptionPane.showMessageDialog(this, "Program Akan Keluar");
        System.exit(0);
    }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql="insert into pelanggan values('"
                    + txtidpelanggan.getText()+"','"
                    + txtnama.getText()+"','"
                    + txtalamat.getText()+"','"
                    + txtnotelp.getText()+"')";
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            tampil_data();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        txtidpelanggan.setText("");
        txtnama.setText("");
        txtalamat.setText("");
        txtnotelp.setText("");
        txtidpelanggan.requestFocus();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();

            String sql = "Select * from pelanggan where id_pelanggan='"+txtcari.getText()+"' or nama_pelanggan='"+txtcari.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
             if (rs.next())
             {
                 txtidpelanggan.setText(rs.getString(1));
                 txtnama.setText(rs.getString(2));
                 txtalamat.setText(rs.getString(3));
                 txtnotelp.setText(rs.getString(4));
                 JOptionPane.showMessageDialog(null,"Data pelanggan : "
                 + txtcari.getText() + " ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
             }
         } catch (Exception e){}
         txtcari.requestFocus();
    }//GEN-LAST:event_btncariActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql="update pelanggan set nama_pelanggan='" + txtnama.getText()
                    +"', alamat ='"+ txtalamat.getText()
                    +"', no_telepon ='"+ txtnotelp.getText()
                    +"' where id_pelanggan='"+ txtidpelanggan.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data berhasil di Koreksi");
            tampil_data();
        }
        catch (Exception e){
        JOptionPane.showMessageDialog(null,"Proses Edit data Gagal");
        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql = "delete from pelanggan where id_pelanggan='" +txtidpelanggan.getText()+"' ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            tampil_data();
        }
        catch (Exception e){
        JOptionPane.showMessageDialog(null,"Proses Penghapusan Gagal");
        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpelangganMouseClicked
        // TODO add your handling code here:
        int tabel = tbpelanggan.getSelectedRow();
        txtidpelanggan.setText(tbpelanggan.getValueAt(tabel, 0).toString());
        txtnama.setText(tbpelanggan.getValueAt(tabel, 1).toString());
        txtalamat.setText(tbpelanggan.getValueAt(tabel, 2).toString());
        txtnotelp.setText(tbpelanggan.getValueAt(tabel, 3).toString());
    }//GEN-LAST:event_tbpelangganMouseClicked

    public void tampil_data(){
        DefaultTableModel tabel=new DefaultTableModel();
        tabel.addColumn("ID PELANGGAN");
        tabel.addColumn("NAMA PELANGGAN");
        tabel.addColumn("ALAMAT");
        tabel.addColumn("NO TELEPON");

        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql="select *from pelanggan";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while (rs.next())
            {
            tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4)});
            }
            tbpelanggan.setModel(tabel);
            }
        catch (Exception e){
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelangganForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pberanda;
    private javax.swing.JPanel pkaryawan;
    private javax.swing.JPanel ppelanggan;
    private javax.swing.JPanel ppembayaran;
    private javax.swing.JPanel ppendataan;
    private javax.swing.JPanel ppengambilan;
    private javax.swing.JTable tbpelanggan;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JLabel txtberanda;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtidpelanggan;
    private javax.swing.JLabel txtkaryawan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JLabel txtpelanggan;
    private javax.swing.JLabel txtpembayaran;
    private javax.swing.JLabel txtpendataan;
    private javax.swing.JLabel txtpengambilan;
    // End of variables declaration//GEN-END:variables
}
