/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yundry;

import java.io.File;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class PembayaranForm extends javax.swing.JFrame {

    /**
     * Creates new form PembayaranForm
     */
    public PembayaranForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_data();
        tampil_pesanan();
        autonumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pberanda = new javax.swing.JPanel();
        txtberanda = new javax.swing.JLabel();
        pkaryawan = new javax.swing.JPanel();
        txtkaryawan = new javax.swing.JLabel();
        ppelanggan = new javax.swing.JPanel();
        txtpelanggan = new javax.swing.JLabel();
        ppendataan = new javax.swing.JPanel();
        txtpendataan = new javax.swing.JLabel();
        ppembayaran = new javax.swing.JPanel();
        txtpembayaran = new javax.swing.JLabel();
        ppengambilan = new javax.swing.JPanel();
        txtpengambilan = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpembayaran = new javax.swing.JTable();
        btnbatal = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtidpembayaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtidpesanan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnamapelanggan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttanggalpembayaran = new javax.swing.JTextField();
        btncetak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttotalbayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txtkembali = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        txtcetak = new javax.swing.JTextField();
        txtjenispaket = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpendataan = new javax.swing.JTable();
        txtcaripesanan = new javax.swing.JTextField();
        btncaripesanan = new javax.swing.JButton();
        btnprintdata = new javax.swing.JButton();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 207, 226));

        jPanel2.setBackground(new java.awt.Color(100, 152, 182));
        jPanel2.setPreferredSize(new java.awt.Dimension(248, 1024));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yundry/Logo1.png"))); // NOI18N

        pberanda.setBackground(new java.awt.Color(215, 206, 156));
        pberanda.setPreferredSize(new java.awt.Dimension(248, 69));
        pberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pberandaMouseClicked(evt);
            }
        });

        txtberanda.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtberanda.setText("BERANDA");
        txtberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtberandaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pberandaLayout = new javax.swing.GroupLayout(pberanda);
        pberanda.setLayout(pberandaLayout);
        pberandaLayout.setHorizontalGroup(
            pberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pberandaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txtberanda)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pberandaLayout.setVerticalGroup(
            pberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pberandaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtberanda)
                .addContainerGap())
        );

        pkaryawan.setBackground(new java.awt.Color(215, 206, 156));
        pkaryawan.setPreferredSize(new java.awt.Dimension(248, 69));
        pkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pkaryawanMouseClicked(evt);
            }
        });

        txtkaryawan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtkaryawan.setText("KARYAWAN");
        txtkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtkaryawanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pkaryawanLayout = new javax.swing.GroupLayout(pkaryawan);
        pkaryawan.setLayout(pkaryawanLayout);
        pkaryawanLayout.setHorizontalGroup(
            pkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkaryawanLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtkaryawan)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pkaryawanLayout.setVerticalGroup(
            pkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkaryawanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtkaryawan)
                .addContainerGap())
        );

        ppelanggan.setBackground(new java.awt.Color(215, 206, 156));
        ppelanggan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppelangganMouseClicked(evt);
            }
        });

        txtpelanggan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpelanggan.setText("PELANGGAN");
        txtpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpelangganMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppelangganLayout = new javax.swing.GroupLayout(ppelanggan);
        ppelanggan.setLayout(ppelangganLayout);
        ppelangganLayout.setHorizontalGroup(
            ppelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppelangganLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtpelanggan)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        ppelangganLayout.setVerticalGroup(
            ppelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppelangganLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpelanggan)
                .addContainerGap())
        );

        ppendataan.setBackground(new java.awt.Color(215, 206, 156));
        ppendataan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppendataanMouseClicked(evt);
            }
        });

        txtpendataan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpendataan.setText("PENDATAAN");
        txtpendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpendataanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppendataanLayout = new javax.swing.GroupLayout(ppendataan);
        ppendataan.setLayout(ppendataanLayout);
        ppendataanLayout.setHorizontalGroup(
            ppendataanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppendataanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtpendataan)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        ppendataanLayout.setVerticalGroup(
            ppendataanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppendataanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpendataan)
                .addContainerGap())
        );

        ppembayaran.setBackground(new java.awt.Color(215, 206, 156));
        ppembayaran.setPreferredSize(new java.awt.Dimension(248, 69));
        ppembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppembayaranMouseClicked(evt);
            }
        });

        txtpembayaran.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpembayaran.setText("PEMBAYARAN");
        txtpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpembayaranMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppembayaranLayout = new javax.swing.GroupLayout(ppembayaran);
        ppembayaran.setLayout(ppembayaranLayout);
        ppembayaranLayout.setHorizontalGroup(
            ppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppembayaranLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtpembayaran)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ppembayaranLayout.setVerticalGroup(
            ppembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppembayaranLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpembayaran)
                .addContainerGap())
        );

        ppengambilan.setBackground(new java.awt.Color(215, 206, 156));
        ppengambilan.setPreferredSize(new java.awt.Dimension(248, 69));
        ppengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppengambilanMouseClicked(evt);
            }
        });

        txtpengambilan.setFont(new java.awt.Font("Charlemagne Std", 0, 26)); // NOI18N
        txtpengambilan.setText("PENGAMBILAN");
        txtpengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpengambilanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ppengambilanLayout = new javax.swing.GroupLayout(ppengambilan);
        ppengambilan.setLayout(ppengambilanLayout);
        ppengambilanLayout.setHorizontalGroup(
            ppengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppengambilanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtpengambilan)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        ppengambilanLayout.setVerticalGroup(
            ppengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppengambilanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(txtpengambilan)
                .addContainerGap())
        );

        btnlogout.setBackground(new java.awt.Color(181, 156, 24));
        btnlogout.setText("LOGOUT");
        btnlogout.setPreferredSize(new java.awt.Dimension(137, 38));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppendataan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(pberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppendataan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ppengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtcari.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtcari.setPreferredSize(new java.awt.Dimension(899, 36));

        btncari.setBackground(new java.awt.Color(253, 234, 127));
        btncari.setText("CARI");
        btncari.setPreferredSize(new java.awt.Dimension(151, 36));
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        tbpembayaran.setFont(new java.awt.Font("Sylfaen", 0, 13)); // NOI18N
        tbpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tbpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpembayaran);

        btnbatal.setBackground(new java.awt.Color(253, 234, 127));
        btnbatal.setText("BATAL");
        btnbatal.setPreferredSize(new java.awt.Dimension(151, 36));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(253, 234, 127));
        btnsimpan.setText("SIMPAN");
        btnsimpan.setPreferredSize(new java.awt.Dimension(151, 36));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel8.setText("Id Pembayaran");

        txtidpembayaran.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtidpembayaran.setPreferredSize(new java.awt.Dimension(433, 36));

        jLabel10.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel10.setText("Id Pesanan");

        txtidpesanan.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtidpesanan.setPreferredSize(new java.awt.Dimension(433, 36));

        jLabel9.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel9.setText("Nama Pelanggan");

        txtnamapelanggan.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtnamapelanggan.setPreferredSize(new java.awt.Dimension(433, 36));

        jLabel11.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel11.setText("Tanggal Pembayaran");

        txttanggalpembayaran.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txttanggalpembayaran.setPreferredSize(new java.awt.Dimension(433, 36));

        btncetak.setBackground(new java.awt.Color(253, 234, 127));
        btncetak.setText("CETAK STRUK PEMBAYARAN");
        btncetak.setPreferredSize(new java.awt.Dimension(151, 36));
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel2.setText("Jenis Paket");

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel3.setText("Jumlah");

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel4.setText("Total Bayar");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel5.setText("Bayar");

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 28)); // NOI18N
        jLabel6.setText("Kembali");

        txtjumlah.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtjumlah.setPreferredSize(new java.awt.Dimension(433, 36));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        jLabel7.setText("Rp");

        txttotalbayar.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txttotalbayar.setPreferredSize(new java.awt.Dimension(433, 36));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        jLabel12.setText("/ Kg");

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        jLabel13.setText("Rp");

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        jLabel14.setText("Rp");

        txtbayar.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtbayar.setPreferredSize(new java.awt.Dimension(433, 36));

        txtkembali.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtkembali.setPreferredSize(new java.awt.Dimension(433, 36));

        btnedit.setBackground(new java.awt.Color(253, 234, 127));
        btnedit.setText("EDIT");
        btnedit.setPreferredSize(new java.awt.Dimension(151, 36));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(253, 234, 127));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        txtjenispaket.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtjenispaket.setPreferredSize(new java.awt.Dimension(433, 36));

        tbpendataan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tbpendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpendataanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbpendataan);

        txtcaripesanan.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        txtcaripesanan.setPreferredSize(new java.awt.Dimension(899, 36));

        btncaripesanan.setBackground(new java.awt.Color(253, 234, 127));
        btncaripesanan.setText("CARI");
        btncaripesanan.setPreferredSize(new java.awt.Dimension(151, 36));
        btncaripesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaripesananActionPerformed(evt);
            }
        });

        btnprintdata.setBackground(new java.awt.Color(253, 234, 127));
        btnprintdata.setText("PRINT DATA");
        btnprintdata.setPreferredSize(new java.awt.Dimension(151, 36));
        btnprintdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(196, 196, 196))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttotalbayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtjenispaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttanggalpembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnamapelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidpesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidpembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(562, 562, 562)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnprintdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnsimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnhapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnbatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcaripesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncaripesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncaripesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcaripesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtidpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtnamapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txttanggalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtjenispaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnprintdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txttotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtberandaMouseClicked
        // TODO add your handling code here:
        BerandaForm rgf = new BerandaForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtberandaMouseClicked

    private void pberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pberandaMouseClicked
        // TODO add your handling code here:
        BerandaForm rgf = new BerandaForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pberandaMouseClicked

    private void txtkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkaryawanMouseClicked
        // TODO add your handling code here:
        KaryawanForm rgf = new KaryawanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtkaryawanMouseClicked

    private void pkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkaryawanMouseClicked
        // TODO add your handling code here:
        KaryawanForm rgf = new KaryawanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pkaryawanMouseClicked

    private void txtpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpelangganMouseClicked
        // TODO add your handling code here:
        PelangganForm rgf = new PelangganForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpelangganMouseClicked

    private void ppelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppelangganMouseClicked
        // TODO add your handling code here:
        PelangganForm rgf = new PelangganForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppelangganMouseClicked

    private void txtpendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpendataanMouseClicked
        // TODO add your handling code here:
        PendataanForm rgf = new PendataanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpendataanMouseClicked

    private void ppendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppendataanMouseClicked
        // TODO add your handling code here:
        PendataanForm rgf = new PendataanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppendataanMouseClicked

    private void txtpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpembayaranMouseClicked
        // TODO add your handling code here:
        PembayaranForm rgf = new PembayaranForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpembayaranMouseClicked

    private void ppembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppembayaranMouseClicked
        // TODO add your handling code here:
        PembayaranForm rgf = new PembayaranForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppembayaranMouseClicked

    private void txtpengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpengambilanMouseClicked
        // TODO add your handling code here:
        PengambilanForm rgf = new PengambilanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txtpengambilanMouseClicked

    private void ppengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppengambilanMouseClicked
        // TODO add your handling code here:
        PengambilanForm rgf = new PengambilanForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ppengambilanMouseClicked

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,
            "Ingin Keluar?",
            "Keluar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, null, null);

        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program Akan Keluar");
            System.exit(0);
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();

            String sql = "Select * from pembayaran where id_pembayaran='"+txtcari.getText()+"' or nama_pelanggan='"+txtcari.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            autonumber();
            if (rs.next())
            {
                txtidpembayaran.setText(rs.getString(1));
                txtidpesanan.setText(rs.getString(2));
                txtnamapelanggan.setText(rs.getString(3));
                txttanggalpembayaran.setText(rs.getString(4));
                txtjenispaket.setText(rs.getString(5));
                txtjumlah.setText(rs.getString(6));
                txttotalbayar.setText(rs.getString(7));
                txtbayar.setText(rs.getString(8));
                txtkembali.setText(rs.getString(9));
                JOptionPane.showMessageDialog(null,"Data pembayaran : "
                    + txtcari.getText() + " ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
            }
        } catch (Exception e){}
        txtcari.requestFocus();
    }//GEN-LAST:event_btncariActionPerformed

    private void tbpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpembayaranMouseClicked
        // TODO add your handling code here:
        int tabel = tbpembayaran.getSelectedRow();
        txtidpembayaran.setText(tbpembayaran.getValueAt(tabel, 0).toString());
        txtidpesanan.setText(tbpembayaran.getValueAt(tabel, 1).toString());
        txtnamapelanggan.setText(tbpembayaran.getValueAt(tabel, 2).toString());
        txttanggalpembayaran.setText(tbpembayaran.getValueAt(tabel, 3).toString());
        txtjenispaket.setText(tbpembayaran.getValueAt(tabel, 4).toString());
        txtjumlah.setText(tbpembayaran.getValueAt(tabel, 5).toString());
        txttotalbayar.setText(tbpembayaran.getValueAt(tabel, 6).toString());
        txtbayar.setText(tbpembayaran.getValueAt(tabel, 7).toString());
        txtkembali.setText(tbpembayaran.getValueAt(tabel, 8).toString());
    }//GEN-LAST:event_tbpembayaranMouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        txtidpesanan.setText("");
        txtnamapelanggan.setText("");
        txttanggalpembayaran.setText("");
        txtjenispaket.setText("");
        txtjumlah.setText("");
        txttotalbayar.setText("");
        txtbayar.setText("");
        txtkembali.setText("");
        txtidpesanan.requestFocus();
        autonumber();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql="insert into pembayaran values('"
            + txtidpembayaran.getText()+"','"
            + txtidpesanan.getText()+"','"
            + txtnamapelanggan.getText()+"','"
            + txttanggalpembayaran.getText()+"','"
            + txtjenispaket.getText()+"','"
            + txtjumlah.getText()+"','"
            + txttotalbayar.getText()+"','"
            + txtbayar.getText()+"','"
            + txtkembali.getText()+"')";
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            tampil_data();
            tampil_pesanan();
            autonumber();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String db = "jdbc:mysql://localhost:3306/yundry";
            String user = "root";
            String password = "";

            con = DriverManager.getConnection(db, user, password);
            Statement stm = con.createStatement();

            try{
                String report = ("D:\\Semester 4\\Project1\\YUNDRY\\src\\yundry\\report1.jrxml");

                HashMap hash = new HashMap();
                hash.put("id", txtcetak.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception rptexcpt){
                System.out.println("Report Can't view because : " + rptexcpt);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PembayaranForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PembayaranForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncetakActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql="update pembayaran set id_pesanan ='" + txtidpesanan.getText()
            +"', nama_pelanggan ='"+ txtnamapelanggan.getText()
            +"', tanggal_pembayaran ='"+ txttanggalpembayaran.getText()
            +"', jenis_paket ='"+ txtjenispaket.getText()
            +"', jumlah ='"+ txtjumlah.getText()
            +"', total_bayar ='"+ txttotalbayar.getText()
            +"', bayar ='"+ txtbayar.getText()
            +"', kembali ='"+ txtkembali.getText()
            +"' where id_pembayaran ='"+ txtidpembayaran.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data berhasil di Koreksi");
            tampil_data();
            tampil_pesanan();
            autonumber();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses Edit data Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql = "delete from pembayaran where id_pembayaran='" + txtidpembayaran.getText()+"' ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            tampil_data();
            tampil_pesanan();
            autonumber();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses Penghapusan Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbpendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpendataanMouseClicked
        // TODO add your handling code here:
        int tabel = tbpendataan.getSelectedRow();
        txtidpesanan.setText(tbpendataan.getValueAt(tabel, 0).toString());
        txtnamapelanggan.setText(tbpendataan.getValueAt(tabel, 2).toString());
        txtjenispaket.setText(tbpendataan.getValueAt(tabel, 5).toString());
        txtjumlah.setText(tbpendataan.getValueAt(tabel, 6).toString());
        txttotalbayar.setText(tbpendataan.getValueAt(tabel, 8).toString());
    }//GEN-LAST:event_tbpendataanMouseClicked

    private void btncaripesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripesananActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();

            String sql = "Select * from pendataan where id_pesanan='"+txtcaripesanan.getText()+"' or nama_pelanggan='"+txtcaripesanan.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next())
            {
                txtidpesanan.setText(rs.getString(1));
                txtnamapelanggan.setText(rs.getString(3));
                txtjenispaket.setText(rs.getString(6));
                txtjumlah.setText(rs.getString(7));
                txttotalbayar.setText(rs.getString(9));
                JOptionPane.showMessageDialog(null,"Data pendataan : "
                    + txtcaripesanan.getText() + " ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
            }
        } catch (Exception e){}
        txtcaripesanan.requestFocus();
    }//GEN-LAST:event_btncaripesananActionPerformed

    private void btnprintdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintdataActionPerformed
        // TODO add your handling code here:
        File reportFile = new File(".");
        String dirr = "";
        
        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql = "select * from pembayaran";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            dirr = reportFile.getCanonicalPath() + "/src/yundry/";
            JasperDesign design = JRXmlLoader.load(dirr + "pembayaran.jrxml");
            JasperReport report =JasperCompileManager.compileReport(design);
            ResultSet rs = pst.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint JPrint = JasperFillManager.fillReport(report, new HashMap(), rsDataSource);
            JasperViewer.viewReport(JPrint, false);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "\nPrint Gagal\n" + ex, "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnprintdataActionPerformed

    public void tampil_data(){
        DefaultTableModel tabel=new DefaultTableModel();
        tabel.addColumn("ID PEMBAYARAN");
        tabel.addColumn("ID PESANAN");
        tabel.addColumn("NAMA PELANGGAN");
        tabel.addColumn("TANGGAL PEMBAYARAN");
        tabel.addColumn("JENIS PAKET");
        tabel.addColumn("JUMLAH");
        tabel.addColumn("TOTAL BAYAR");
        tabel.addColumn("BAYAR");
        tabel.addColumn("KEMBALI");
        

        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql="select *from pembayaran";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while (rs.next())
            {
            tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),
                rs.getString(9)});
            }
            tbpembayaran.setModel(tabel);
            }
        catch (Exception e){
        }
    }
    
    public void tampil_pesanan(){
        DefaultTableModel tabel=new DefaultTableModel();
        tabel.addColumn("ID PESANAN");
        tabel.addColumn("NAMA KARYAWAN");
        tabel.addColumn("NAMA PELANGGAN");
        tabel.addColumn("TANGGAL PESANAN");
        tabel.addColumn("RENCANA AMBIL");
        tabel.addColumn("JENIS PAKET");
        tabel.addColumn("JUMLAH");
        tabel.addColumn("KETERANGAN");
        tabel.addColumn("TOTAL BAYAR");

        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            String sql="select *from pendataan";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while (rs.next())
            {
            tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),
                rs.getString(9)});
            }
            tbpendataan.setModel(tabel);
            }
        catch (Exception e){
        }
    }
    
    public void autonumber(){
        try {
            java.sql.Connection conn = (java.sql.Connection)yundry.connection.getConnection();
            Statement pst = conn.createStatement();
            String sql="select max(right(id_pembayaran,3)) as no from pembayaran";
            ResultSet rs = pst.executeQuery(sql);
            
            while (rs.next())
            {
            if(rs.first() == false){
                txtidpembayaran.setText("BYR001");
            }else{
                rs.last();
                int set_id = rs.getInt(1)+1;
                String no = String.valueOf(set_id);
                int id_next = no.length();
                for(int i=0; i<3-id_next; i++){
                    no = "0" + no;
                }
                txtidpembayaran.setText("BYR"+ no);
            }   
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Auto Number Gagal", "Error", 2);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembayaranForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembayaranForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembayaranForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembayaranForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembayaranForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncaripesanan;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnprintdata;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pberanda;
    private javax.swing.JPanel pkaryawan;
    private javax.swing.JPanel ppelanggan;
    private javax.swing.JPanel ppembayaran;
    private javax.swing.JPanel ppendataan;
    private javax.swing.JPanel ppengambilan;
    private javax.swing.JTable tbpembayaran;
    private javax.swing.JTable tbpendataan;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JLabel txtberanda;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtcaripesanan;
    private javax.swing.JTextField txtcetak;
    private javax.swing.JTextField txtidpembayaran;
    private javax.swing.JTextField txtidpesanan;
    private javax.swing.JTextField txtjenispaket;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JLabel txtkaryawan;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtnamapelanggan;
    private javax.swing.JLabel txtpelanggan;
    private javax.swing.JLabel txtpembayaran;
    private javax.swing.JLabel txtpendataan;
    private javax.swing.JLabel txtpengambilan;
    private javax.swing.JTextField txttanggalpembayaran;
    private javax.swing.JTextField txttotalbayar;
    // End of variables declaration//GEN-END:variables
}
